language: node_js
node_js: 7
cache:
  directories:
  - node_modules
  - bower_components
  - "${NVM_PATH}_modules"
env:
  matrix:
- CXX=g++-4.8
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-4.8
install:
- npm install
script: echo "Deploying!"
before_deploy: npm run build
deploy:
- provider: firebase
  skip_cleanup: true
  on:
    branch: master
  project: david-bara-wedding
  token:
    secure: CaZxug7kSVjaldS1YkjBcZh5FlrHLZEfnnqIDd9FHppX9sFF0bavqHJkJO5tsC5bepEaC75z+CIuUc1r4UvhPg8V12aFTZ3H9suPtCESBVgrEJ1NFRPIzCRf+gvSRTdb46ZEnMI0/CkLxm5CGnWIGw3WIF3hCjk/oVZfWgnmC+C+m/h4PlkolUV3k8EySDqjro1ksJeYQ0Si0HlMEZutPCrz3xiRNv0Y5UJWDwTdpQ9IlGBcCSeac906FeLaX+UPWZ0QZkGyx13iyratMtCdw4TF4Wx3wrPJpuSij/BJaXMS/b+hRUsWsfmJBn50vn+IyEtgZNRNN6CbkBAh+TqPPWO3a9UR3RQvtK3j6PCMJrzJNPg+AyBT+ZLhlniBTYQ8fmc4WIggck708wh4nkVl/Lg/e1C3brxyHG4e0Q2jrsAm9zVKJMyhZDCDCrEOGtHvvsRwbdhvPSzRHkTRzpHIy4CM9sQ7X4oiltYq7qHSsKCi3OqILv2Ce70NFgSQPljDO7AOvERQ39/A2ou2JLJ2DDD7jTD2p1MLbnLxWzWJzs5fy85ziel5bvTcRkvgnjVmd5Ek4lk9sV8DsBK9IsfpIWtFjCm6IgK7ixv8gKllElRTUrvaNb7rvJnXp3Q9kUfjta2Ce4y074cwUqYZA6lLSTmaJyL8n9pcQp2H+Z8BBAQ=